######### NORMAL OPERATION  ###########
@baseUrl = http://localhost:3000

### Read all films
GET {{baseUrl}}/films

### Read all films with this minimum duration
GET {{baseUrl}}/films?minimum-duration=160

### Read the film identified by an id in the menu
GET  {{baseUrl}}/films/2


### Create a drink
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title":"Harry Potter",
    "director" : "J K Rowling",
    "duration" : 60,
    "budget" : 250,
    "imageUrl":"https://upload.wikimedia.org/wikipedia/commons/6/6e/Harry_Potter_wordmark.svg" 
}

### Delete a film
DELETE {{baseUrl}}/films/4



### Update the drink identified by 2
PATCH {{baseUrl}}/films/2
Content-Type: application/json

{
    "title":"Titanic : Remake"
}


### PUT method
PUT {{baseUrl}}/films/5
Content-Type: application/json

{
    "title":"Fun title",
    "director": "Fun author",
    "duration": 420,
    "budget": 420
}